name: covid_app
description: A new Flutter application.


# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
environment:
  sdk: ">=2.2.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  pie_chart: ^1.3.0
  http: ^0.12.2
  avatar_glow: ^1.2.0
  time_formatter: ^1.0.0
  simple_splashscreen: ^0.1.3
  progress_indicators: ^0.1.5
  show_up_animation: ^1.0.2
  shared_preferences: ^0.5.10
  line_icons: ^0.2.0
  url_launcher: ^5.5.3
  google_fonts: ^1.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #  - images/a_dot_ham.jpeg


  fonts:
     - family: SourceSansPro
       fonts:
         - asset: assets/Fonts/SourceSansPro-Black.ttf
   #      - asset: assets/Fonts/SourceSansPro-BlackItalic.ttf

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
